### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by oO-u-Oo** [TripleFrequency/AthamePlugin.Deezer#10]
Your plugin says "Signed in as"  without having logged in.

**Comment by ThePlayingGoblin** [comment]
That's because an account is not required to use this plugin. Its just a visual that does not affect the plugin.

**Comment by jonaaa20** [comment]
1- Creating a new issue isn't necessary
2- You don't need a account as the dev already mentioned it.

**Comment by oO-u-Oo** [comment]
It would be good to say at least something such as "Signed in as not exist @email.com" or "Signed out" so as not to confuse people and think badly, for me there is no problem. ;)

**Comment by TripleFrequency** [comment]
This is an issue with the main Athame application. I have submitted a pull request here: https://github.com/svbnet/Athame/pull/90 to fix this issue. If I don't make the plugin implement an authentication system, regardless of if it does anything, then it doesn't work.
