### ISSUE TITLE
Language

### ISSUE THREAD

**Issue by oO-u-Oo** [TripleFrequency/AthamePlugin.Deezer#11]
In addition to english do you support in other languages?, I mean the languages you speaks to contact him, I do not mean your plugin.

**Comment by TripleFrequency** [comment]
I don't completely follow what you mean here, but the plugin and Athame do not support localization. You would have to post an issue on the Athame repository.

**Comment by oO-u-Oo** [comment]
What I'm trying to tell you is not related to Athame or its complement, I mean the languages you speak, I would like to contact you in my language so that there are no misunderstandings, I do not speak English.

**Comment by TripleFrequency** [comment]
Oh! I also speak Spanish. Sorry the translation in your first message was not very clear, as it seemed you were trying to contact Joe/svbnet. What is your primary language, if I may ask as well?

**Comment by oO-u-Oo** [comment]
Then we will understand perfectly, spanish is my language.

**Comment by TripleFrequency** [comment]
Tendrás que perdonarme, porque mi español no es fantastico. Todavía estoy aprendiendo. :)

**Comment by oO-u-Oo** [comment]
We communicate in English,, do not worry, if you do not understand, please tell me.
