### ISSUE TITLE
ArgumentOutOfRangeException: Index was out of range

### ISSUE THREAD

**Issue by bascurtiz** [TripleFrequency/AthamePlugin.Deezer#13]
Great idea to write a Plugin for Athame!

But, everytime, I try to grab a Playlist (10 tracks), I get the following error: https://gyazo.com/e315f7fab66791f0059f53f8b557b0ac

Using Win10 x64 + Athame 0.4.5 + AthamePlugin.Deezer 1.2.4

U can try urself, here's a Playlist generated by a member of the staff @ Deezer (50+ tracks):
http://www.deezer.com/playlist/2349326262

When d/ling a track-only from such playlist, all went good.
So might be duplicate of #3

**Comment by TripleFrequency** [comment]
It if failing because the artists have an & in their names. This was a weakness of an earlier bugfix. I have corrected this with 055c698. I have also pushed a new release with this fix, [Version 1.2.5](https://github.com/TripleFrequency/AthamePlugin.Deezer/releases/latest).
