### ISSUE TITLE
vs. / and / featuring

### ISSUE THREAD

**Issue by oO-u-Oo** [TripleFrequency/AthamePlugin.Deezer#14]
Since is practically same, I recommend that it be replaced by the &, the 3 appear in the names of the artists.

Examples
http://www.deezer.com/album/7384612
http://www.deezer.com/album/964707
http://www.deezer.com/track/123240374

By the way, about the link of the track, the names of the artists are duplicated.

*I have tested them with version 1.2.5

**Comment by TripleFrequency** [comment]
I am not seeing any issues with the links you provided me.

With the first link, Deezer Provides solely "Michael Brixx vs. Carl Cox" *as* the artist. This means that I have no other information about who the artists actually are, and the names won't duplicate, which would be the main issue.

For the second link, the same applies, "Carl Cox Featuring Savanah Blount" is simply the artist name, and I have no other information.

Lastly, I have no issues with the final track. It displays as "Tiësto & Ummet Ozcan" for me.

**Comment by oO-u-Oo** [comment]
The link of the track the names of the artists are duplicated with the version 1.2.5 but they do not duplicate with the version 1.2.4, the vs. of "Michael Brixx vs. Carl Cox" (they are two artists)  I should replace it for & , "Carl Cox Featuring Savanah Blount" They are also two artists.

**Comment by TripleFrequency** [comment]
Could you provide images of this happening? I can't reproduce this issue, and what you describe (with duplicates) I can't see. Also, as I was saying, while I *could* replace vs./and/featuring with &, it would be inconsistent with the Deezer API, and a bad choice overall.

Like I said previously, I have no information that actually separates these artists, they are provided as a singular artist. In most other cases (with duplicates), I could do something because I had information about the artists as well. For example, I could fix it if I was given an artist list like "Michael Brixx", "Carl Cox", "Michael Brixx vs. Carl Cox". But, instead, I am given only "Michael Brixx vs. Carl Cox".

**Comment by oO-u-Oo** [comment]
MICHAEL BRIXX:
http://classic.beatport.com/artist/michael-brixx/388671

CARL COX:
http://classic.beatport.com/artist/carl-cox/6821

**Comment by TripleFrequency** [comment]
Español:
No entiendes. Cuando introduces una canción en la aplicación, ella busca en Deezer para la información. Estoy diciendo que *Deezer* no le da la información para los músicos. Deezer solo le da uno músico, por eso no sé (por seguro) que hay dos músicos. No puedo cambiar esto, porque sí hay un músico con "vs." normalmente, la cambia corromperá la información de este músico.

English
I don't think you follow. When you post a link to a song, the application goes to the Deezer API to get information. I am saying that *Deezer* is not providing additional information. The API returns that there is only one artist (with their names combined). I can't do anything with that information other than report it how it is. If I replace "vs." as a blanket rule, it could cause issues if an actual artist has that in their name, so I won't.

**Comment by oO-u-Oo** [comment]
Do not worry, I do it with mp3tag and the stevehero script that I'm going to customize and in Spanish.

Duplicate artists with version 1.2.5:
https://i.imgur.com/lflRNW2.png

**Comment by TripleFrequency** [comment]
This is my mistake. I realize that right before I pushed the release, I modified the comparison algorithm, but not everywhere I needed to. So, determining the artist always failed. There is a new version (1.2.6) which fixes this, and adds another unrelated fix.
