### ISSUE TITLE
Playlist suggestion + .m3u

### ISSUE THREAD

**Issue by ThePlayingGoblin** [TripleFrequency/AthamePlugin.Deezer#18]
I would like to see an option to download a .m3u playlist file that will create a playlist of the downloaded album or user made playlist by its manual order. I would also like to see an option when downloading user-made playlists for all of the tracks to go into one folder named after the playlist, instead of a bunch of folders named after the song, ep or album. This was something that used to be on deezloader and that I would like to see on this plugin.

**Comment by TripleFrequency** [comment]
Very interesting idea, but I don't believe I can do this within the scope of Athame, or at least I shouldn't. Any solution I could come up with would likely be quite convoluted, meant to directly circumvent many of Athame's systems. If you could elaborate a bit more, provide an example perhaps, and explain the usefulness of this, I could look into a bit more.
