### ISSUE TITLE
Special characters

### ISSUE THREAD

**Issue by oO-u-Oo** [TripleFrequency/AthamePlugin.Deezer#19]
The artist **Ø [PHASE]** it does not put it correctly.

http://www.deezer.com/track/421758752
http://classic.beatport.com/track/detonation-vertex-original-mix/9887436

**Comment by TripleFrequency** [comment]
I cannot do anything about this, it is an issue with Deezer. Deezer provides the artist's name as "[Ø](http://www.deezer.com/en/artist/5168234)", and I can't just append [PHASE]. The algorithm for joining artists without duplicates wouldn't be able to accurately pick the correct artist if I tried to use the name provided.
