### ISSUE TITLE
Playlist music count mismatch

### ISSUE THREAD

**Issue by rafaeldamasceno** [TripleFrequency/AthamePlugin.Deezer#22]
Playlist is http://www.deezer.com/us/playlist/3866576306

Deezer reports 299 tracks, actual downloaded tracks are 298. 

I didn't count them in Athame (obviously), just in the output folder. No errors or logs. Perhaps it would be a good feature to be added to it.

**Comment by rafaeldamasceno** [comment]
There is, in fact, a duplicate track in the playlist. Maybe there should be an indicator for this situation, as I do not know of any service that can detect duplicate tracks on Deezer playlists... Thankfully it was a converted playlist from Spotify and I found it there. Please close the issue if you feel there's nothing to be done for this.

**Comment by TripleFrequency** [comment]
I can't access the playlist you provided, so I can't diagnose the issue unless I have that.

**Comment by rafaeldamasceno** [comment]
Hey, sorry about that. I deleted it since because I keep them updated from my Spotify ones. To replicate, simply add the same song to a playlist twice. I'm not sure what exactly I wanted Athame to do in this case, though :P It's just that in the midst of a few hundred songs, it's not exactly immediate why there was one less track than in the playlist, even though it was just the same track twice.
