### ISSUE TITLE
Artists

### ISSUE THREAD

**Issue by oO-u-Oo** [TripleFrequency/AthamePlugin.Deezer#26]
Duplicated artists with version 1.3 
deezer.com/album/14002236

**Comment by TripleFrequency** [comment]
I fixed this with 1.3-A2. Basically, I was removing special characters for the comparison of artists too early, and so the & symbol was stripped out before it was actually used to split the names up.

**Comment by oO-u-Oo** [comment]
Thanks so much !, I have decided to remove the link. ;)

**Comment by TripleFrequency** [comment]
@oO-u-Oo You really shouldn't remove the links you leave in these posts. As I go back to verify I won't break things with certain changes, I find that there are no links to test with.

Just something to consider, no big deal either way, but it could be useful to people all around if you leave them.

**Comment by oO-u-Oo** [comment]
Deezer has reported many programs hosted on github so it is best to eliminate them to avoid getting into legal problems.
github.com/github/dmca/blob/master/2017/2017-02-06-Deezer.md
