### ISSUE TITLE
Original artist

### ISSUE THREAD

**Issue by oO-u-Oo** [TripleFrequency/AthamePlugin.Deezer#27]
Correct file name:
Nicolas Cuer - i Love Marie (Axel Karakasis Remix)

Incorrect file name:
Axel Karakasis - i Love Marie (Axel Karakasis Remix)

deezer.com/track/434637842
classic.beatport.com/track/i-love-marie-axel-karakasis-remix/1393815

Tidal if you writes it correctly.
listen.tidal.com/album/81832796

**Comment by TripleFrequency** [comment]
This has been fixed, and will be in the next release.

**Comment by oO-u-Oo** [comment]
I never tire of giving you Thanks. ;),  if it were not for all the mistakes made by the record companies, the application would be perfect.

Greetings .
