### ISSUE TITLE
ID3v1

### ISSUE THREAD

**Issue by oO-u-Oo** [TripleFrequency/AthamePlugin.Deezer#28]
¿Can do possible not write tags in ID3v1?, only in ID3v2.

**Comment by jonaaa20** [comment]
Deezer files writes at id3v2, you can write the file with mp3tag, so, you can have id3v1 and v2 in the same file.

**Comment by oO-u-Oo** [comment]
I said only ID3v2.

**Comment by jonaaa20** [comment]
You can remove the v1 with mp3tag too... Mp3tag does the job.

**Comment by oO-u-Oo** [comment]
Se perfectamente que se puede hacer con mp3tag pero si se puede evitar aplicaciones de terceros muchisimo mejor.

**Comment by jonaaa20** [comment]
Hmm... But for now you can 'fix' it on mp3tag until @TripleFrequency fixes it

**Comment by TripleFrequency** [comment]
@oO-u-Oo I cannot change this. Athame writes the tags, I just provide the information. You will have to open an issue in [svbnet/Athame](https://github.com/svbnet/Athame).
