### ISSUE TITLE
Beatport

### ISSUE THREAD

**Issue by oO-u-Oo** [TripleFrequency/AthamePlugin.Deezer#29]
If the Beatport tags were add in the deezer plugin it would be fantastic.
oauth-api.beatport.com
forums.mp3tag.de/index.php?showtopic=14479

**Comment by jonaaa20** [comment]
I don't want to be rude but if you want beatport tags, remove the deezer tags then tag it with beat port source...

**Comment by oO-u-Oo** [comment]
@jonaaa20
¿Te he pedido yo a ti tu opinion? ¿Te llamas TripleFrequency?
