### ISSUE TITLE
Playlists Inexplicably Have Random Failures

### ISSUE THREAD

**Issue by TripleFrequency** [TripleFrequency/AthamePlugin.Deezer#3]
In large playlists (or any, really), some songs fail to download without any real reason.

By sniffing HTTP traffic, you can see that these failures are actually 403 errors (Forbidden). In the case of Deezer, this normally means the URL to the (encrypted) track is invalid, but there is no obvious reason this should happen under normal use.

Due to its infrequent occurrence, one possible solution is to simply re-download the track information if it fails, then calculate the URL again.

It is notable that directly getting these tracks is successful, but in the playlist they may fail.

**Comment by ThePlayingGoblin** [comment]
This playlist is a good example:
http://www.deezer.com/us/playlist/1824605662

**Comment by TripleFrequency** [comment]
So after quite a bit of testing, I have narrowed this issue down to a few different causes.

The most interesting being the fact that in the main API, some tracks return "No Data," as if they are not attached to their tracks correctly.
Example: Imagine Dragons - Thunder (the track) says its album ID is `40765801`
Well, if you go to http://api.deezer.com/album/40765801, you get a no data error.

Another possible issue is regions. Not all songs are available everywhere. I am playing around with this for now, but I will likely have to find a way to efficiently determine if the file is downloadable based on region.

I am working on these issues currently, and hope to find decent work-arounds for them in a timely manner.

**Comment by TripleFrequency** [comment]
I marked this as an enhancement also, because now that the issue has been identified as a mix of invalid API information and regional limitations, the enhancement part is that I want to improve the track unavailability detection.

**Comment by TripleFrequency** [comment]
This issue is fixed in Version 1.2.7 Release Candidate 3. Please try this out, and report back any issues.

What was happening was very different than originally thought. Basically, if a track had multiple releases, Deezer only stores one version of the file, so when you get a track's info, it will return the download track's info if applicable. In the new version, it uses the "fallback" track's information to download the file, which should fix this issue entirely.

Please report if you encounter tracks that do not download with 1.2.7-RC3.

**Comment by megapilot** [comment]
RE: region blocking
According the changelog of the "boerse deezer downloader" mentioned [here](https://github.com/svbnet/Athame/issues/100), country limitations apparently can be circumvented.
Would need to get the app and wireshark / decompile to see how it is done, unless someone has an idea.

**Comment by TripleFrequency** [comment]
My previous comment on the matter didn't clear up that the one before it was not accurate. From what I have seen after my fix to the issue, regional issues aren't really existent here. You should be able to download tracks, even if they are supposed to be region locked.
