### ISSUE TITLE
"Value of 2 is not valid for index" when dequeuing songs

### ISSUE THREAD

**Issue by monotron** [TripleFrequency/AthamePlugin.Deezer#33]
While downloading a long queue of albums from Deezer, I encountered this error:

![Image of stack trace](https://captr.us/i/s934k.png)

Removing items from the queue did not resolve the issue - I had to restart Athame to be able to download again, of course having to re-add all the albums in the queue. I can provide further information if it is needed; if this is a bug with Athame itself, apologies.

**Comment by TripleFrequency** [comment]
I believe this may be an issue with athame itself. I think I have seen this myself once or twice. Did you remove items from the queue *before* downloading?

**Comment by monotron** [comment]
Alright, I'll open an issue on Athame's repo.
This was the result of Athame trying to remove items from the queue when they had finished downloading.
