### ISSUE TITLE
Image Size

### ISSUE THREAD

**Issue by UserForTheOnlyTopic** [TripleFrequency/AthamePlugin.Deezer#35]
Add please an option "None" into Image Size

**Comment by fabriccioguzman** [comment]
hello, it is impossible to have option none in image size, the only way is to add an option that integrates or does not integrate a cover image, but this seems to be a problem of athame and not plugin

**Comment by TripleFrequency** [comment]
Yes, this would be a better suited request for Athame to not embed any cover images, so that people could have the option for all plugins.

**Comment by UserForTheOnlyTopic** [comment]
@fabriccioguzman Hello! No, it's not a problem at all. I made it when i was using one of old versions of this plugin, but after a new version appeared, i have used new versions and removed code, and didn't want to compile libs again since i'd have to open a tool, change some code and compile libs again after each new version. It's very uncomfortable, it's much easier to add the option into main code of the plugin to prevent such "sufferings".
