### ISSUE TITLE
Retain Playlist Order And Artwork

### ISSUE THREAD

**Issue by megapilot** [TripleFrequency/AthamePlugin.Deezer#36]
Would it be within the scope of this plugin to optionally tag playlist downloads with playlist name as %album%, original playlist artwork and retain the track order of the playlist? Would be great e.g. for curated playlists.
Or does the Deezer API simply not expose this information?

**Comment by TripleFrequency** [comment]
The Deezer API exposes this information, but it is more of a limitation with Athame. You would need to open an issue in that repository.
