### ISSUE TITLE
Image size

### ISSUE THREAD

**Issue by oO-u-Oo** [TripleFrequency/AthamePlugin.Deezer#5]
The size of the chosen cover does not correspond to the embedment.

**Comment by TripleFrequency** [comment]
This was an error on my part, and was caused by the ambiguity of the Deezer API. I simply didn't match the sizes together properly. I will fix this in the next release.

**Comment by TripleFrequency** [comment]
One other note I wanted to make about this. After you download an album (and the image is also downloaded), you have to restart Athame before you can re-download the album again with a different image size.

This is a limitation with Athame because of how it caches images. You can download a different album with a different size without restarting, though.

**Comment by oO-u-Oo** [comment]
Thanks so much !, tomese las cosas con calma, actualizas demasiado rapido, do not hurry.:)(

**Comment by oO-u-Oo** [comment]
Please, do not eliminate the size 500x500, I would appreciate it very much, Thank you!

**Comment by TripleFrequency** [comment]
I will re-write the thumbnail system so I can add these sizes. I am currently using a shorthand system they have that allows me to easily redirect (so standard sizes like small, medium, big, and xl). I can modify this to support more, though.

**Comment by oO-u-Oo** [comment]
Leave it if it is a lot of work, I think that it is not necessary a lot of big size since the quality when they are enlarged is very bad, so I think that with those two sizes it is more than enough .

**Comment by TripleFrequency** [comment]
Yes, I noticed as well that the covers are quite poor quality on Deezer.

**Comment by TripleFrequency** [comment]
@oO-u-Oo Relating to your request for other image sizes, it has been added in the new version (1.3-RC1)

**Comment by oO-u-Oo** [comment]
Thanks so much !

Tell me what you think of this, instead of adding so many options add only tthree size options (500x500 / 1000x1000) and the third option to give people the option of manually putting the size.

**Comment by TripleFrequency** [comment]
It's more of a temporary solution, because I didn't want to write a system to parse and validate the input 😛. I'll probably add this later.

**Comment by oO-u-Oo** [comment]
Todo lo que usted haga y decida me parecera todo perfecto, bastante haceis los tres por nosotros.

**Comment by TripleFrequency** [comment]
Gracias, solo quiero que todas tengan una buena experiencia con el plugin.

**Comment by oO-u-Oo** [comment]
Habla usted un perfecto español. ;)

Cuando el traductor de google no me convence una traducción decido contactar con usted en español,
