### ISSUE TITLE
Putting original artist as featured in some albums.

### ISSUE THREAD

**Issue by kannibleklown** [TripleFrequency/AthamePlugin.Deezer#6]
as seen by this screenshot, some albums seem to put the original artist as a featured artist as well, when it shouldn't.       https://i.imgur.com/X7JPMX9.png

**Comment by TripleFrequency** [comment]
I fixed this with the latest commit. I can't publish a new release or anything until I am home this evening (12 hours or so), but feel free to use the attached release if you would like to test the solution for me.
[Deezer.zip](https://github.com/TripleFrequency/AthamePlugin.Deezer/files/1521378/Deezer.zip)
