### ISSUE TITLE
Tags

### ISSUE THREAD

**Issue by oO-u-Oo** [TripleFrequency/AthamePlugin.Deezer#8]
Recommended tag in URL:
https://deezer.com

Unnecessary tags:
Disc # / Track # / Album Artist

**Comment by TripleFrequency** [comment]
I don't follow what the issue is here, could you explain a bit more?

**Comment by oO-u-Oo** [comment]
They are the tags that should be added and not added in the tracks.

**Comment by TripleFrequency** [comment]
I can't modify these. They are required by Athame itself, and URLs are not supported.

**Comment by oO-u-Oo** [comment]
https://github.com/TripleFrequency/AthamePlugin.Deezer/issues/7#issuecomment-348659394
